import os
from dotenv import load_dotenv
load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("INSTRUCTOR_BOT_TOKEN", "")
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite+aiosqlite:///./nomad.db")
ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "admin")

MAX_ACTIVE_BOOKINGS = 3
TRAINING_PRICE_MANUAL = 25000
TRAINING_PRICE_AUTOMATIC = 30000
EXAM_PRICE = 15000
EXAM_DURATION_MINUTES = 90
TRAINING_DURATION_MINUTES = 60
RATING_GOOD_THRESHOLD = 4.5
RATING_BAD_THRESHOLD = 3.5
LOW_RATING_NOTIFICATION_THRESHOLD = 3.5
RATING_DECAY = 0.1
RATING_BOOST = 0.1
BLACKLIST_THRESHOLD = 3
REFERRAL_DISCOUNT_PERCENT = 10
INITIAL_RATING = 5.0
